### PR TITLE
feat: support deploy with azd

### PR DESCRIPTION
**Pull request by frankliu20**
with this support, you can deploy the whole project by running
`azd up`

### CODE REVIEW

**Review by pmalarme — CHANGES_REQUESTED** [review]
Hi Frank,

Good update. I will do the following to improve it:

- [x] Add the update of the runtime to java and enable java metrics for the 4 Java Spring micro-services
- [ ] Update the documentation and the deploy script to include the change of location of deploy.bicep
- [x] Maybe we should remove the deploy script as we have azd instead? What do you think?
- [ ] Add azd documentation for fast deployment in the main

**Review by SandraAhlgrimm — DISMISSED** [review]
please update the README.md

**Comment by SandraAhlgrimm** [comment]
> Hi Frank,
> 
> Good update. I will do the following to improve it:
> 
> * [ ]  Add the update of the runtime to java and enable java metrics for the 4 Java Spring micro-services
> * [ ]  Update the documentation and the deploy script to include the change of location of deploy.bicep
> * [ ]  Maybe we should remove the deploy script as we have azd instead? What do you think?
> * [ ]  Add azd documentation for fast deployment in the main

documentation should be there, for the rest let's do this in another PR

**Review by pmalarme — APPROVED** [review]

**Comment by pmalarme** [comment]
Documentation will be done in a separated PR. The legacy script will be removed too

**Pull request merged**
